#!/usr/bin/env python3
"""Generate the audio_assets seed SQL for Phase 2.

Run once to produce supabase/seed/0002_audio_assets.sql, then paste it into the
Supabase SQL Editor (after the snippet files are uploaded to the bucket).

    python -m scripts.central_db.generate_audio_assets_sql

Only emits rows for audio files that exist on disk. Idempotent on the DB side
(ON CONFLICT (bucket, storage_path) DO NOTHING).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.central_db.audio_assets import audio_assets_rows  # noqa: E402

DEFAULT_DB = REPO_ROOT / "db" / "lighting-ai-db.json"
DEFAULT_OUT = REPO_ROOT / "supabase" / "seed" / "0002_audio_assets.sql"
_COLS = ["song_id", "kind", "bucket", "storage_path", "bar_num", "part_id"]


def _lit(v) -> str:
    if v is None:
        return "null"
    if isinstance(v, (int, float)) and not isinstance(v, bool):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def build_sql(db: dict, repo_root: Path) -> str:
    rows = audio_assets_rows(db, repo_root)
    out = [
        "-- GENERATED by scripts/central_db/generate_audio_assets_sql.py — do not edit.",
        "-- Phase 2: register uploaded snippet/playalong audio. Paste after uploading",
        "-- the audio/ folder into the 'snippets' bucket, then Run.",
        "begin;",
    ]
    for r in rows:
        vals = ", ".join(_lit(r[c]) for c in _COLS)
        out.append(
            f"insert into audio_assets ({', '.join(_COLS)}) values ({vals}) "
            f"on conflict (bucket, storage_path) do nothing;"
        )
    out.append("commit;")
    out.append("")
    return "\n".join(out), len(rows)


def main(argv: list[str] | None = None) -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", type=Path, default=DEFAULT_DB)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--repo-root", type=Path, default=REPO_ROOT,
                    help="root that contains the audio/ folder (for existence checks)")
    args = ap.parse_args(argv)

    db = json.loads(args.db.read_text(encoding="utf-8"))
    sql, n = build_sql(db, args.repo_root)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(sql, encoding="utf-8")
    print(f"Wrote {args.out} ({n} audio_assets rows).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
