#!/usr/bin/env python3
"""Generate a plain-SQL seed of the whole song DB for the Supabase SQL Editor.

This is the no-terminal / no-key alternative to import_to_supabase.py: run once
to produce supabase/seed/0001_seed_from_json.sql, then paste that file into the
Supabase SQL Editor (which runs privileged and bypasses RLS) and press Run.

    python -m scripts.central_db.generate_seed_sql

Idempotent on the DB side (every insert has ON CONFLICT DO NOTHING), so it can
be re-run after the schema without creating duplicates.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.central_db.transform import db_json_to_rows  # noqa: E402

DEFAULT_DB = REPO_ROOT / "db" / "lighting-ai-db.json"
DEFAULT_OUT = REPO_ROOT / "supabase" / "seed" / "0001_seed_from_json.sql"

_SONG_COLS = ["id", "name", "artist", "bpm", "music_key", "year",
              "pick", "gema_nr", "duration", "duration_sec", "notes"]
_BAR_COLS = ["bar_id", "song_id", "bar_num", "lyrics", "audio", "has_accents", "instrumental"]
_ACCENT_COLS = ["accent_id", "bar_id", "pos_16th", "type", "notes"]


def _lit(v) -> str:
    """Render a Python value as a SQL literal."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def _jsonb(v) -> str:
    return "'" + json.dumps(v, ensure_ascii=False).replace("'", "''") + "'::jsonb"


def _insert(table: str, cols: list[str], row: dict, pk: str) -> str:
    vals = ", ".join(_lit(row[c]) for c in cols)
    return f"insert into {table} ({', '.join(cols)}) values ({vals}) on conflict ({pk}) do nothing;"


def build_sql(db: dict) -> str:
    rows = db_json_to_rows(db)
    out: list[str] = [
        "-- GENERATED by scripts/central_db/generate_seed_sql.py — do not edit by hand.",
        "-- Paste into the Supabase SQL Editor after 0001_initial_schema.sql, then Run.",
        "begin;",
    ]
    out += [_insert("songs", _SONG_COLS, r, "id") for r in rows["songs"]]
    out += [
        f"insert into song_detail_lighting (song_id, detail) values "
        f"({_lit(r['song_id'])}, {_jsonb(r['detail'])}) on conflict (song_id) do nothing;"
        for r in rows["song_detail_lighting"]
    ]
    out += [_insert("bars", _BAR_COLS, r, "bar_id") for r in rows["bars"]]
    out += [_insert("accents", _ACCENT_COLS, r, "accent_id") for r in rows["accents"]]
    a = rows["app_state"]
    out.append(
        f"insert into app_state (id, version, band, setlist, meta) values "
        f"(1, {_lit(a['version'])}, {_lit(a['band'])}, {_jsonb(a['setlist'])}, {_jsonb(a['meta'])}) "
        f"on conflict (id) do nothing;"
    )
    out.append("commit;")
    out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", type=Path, default=DEFAULT_DB)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args(argv)

    db = json.loads(args.db.read_text(encoding="utf-8"))
    sql = build_sql(db)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(sql, encoding="utf-8")
    n = sql.count("\ninsert ")
    print(f"Wrote {args.out} ({len(sql) / 1024:.0f} KB, {n} insert statements).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
